try {
    //let x = noExiste()
    throw('Este es mi error')
} catch (error) {
    alert("Lo sentimos se ha producido un error " + error)
}

